### ISSUE TITLE
Is "DistributedSampler" necessary？

### ISSUE THREAD

**Issue by Kungbohan** [PatrickHua/SimSiam#16]
Hello,
I find that there is no "DistributedSampler" in the code.
Is it a normal setting?
I think this setting would make the model run the same data twice (or the number of GPU) in a single epoch (because the shuffle is True.).
I'm not sure if this is normal. 
Thank you very much.

**Comment by PatrickHua** [comment]
I've changed the code. It's someone else's pull request.
