### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by talsgambit** [PatrickHua/SimSiam#18]
First of all, I want to thank you for this great project! I am a phD student in the field of Deep Learning and would really like to include your implementation in my experiments. Unfortunately, what stops me from doing so is that you did not provide a license yet. Would it be possible for you to add a license for this project such as the MIT license? I would greatly appreciate that and, of course, properly cite your work.

**Comment by PatrickHua** [comment]
Thanks for reminding me ~ I have added MIT license.

**Comment by talsgambit** [comment]
Great! Thank you very much!
