### ISSUE TITLE
Looking for Phd positions ...

### ISSUE THREAD

**Issue by PatrickHua** [PatrickHua/SimSiam#20]
Previously I was working on my graduate school application. 

I know there are several bugs in the code and I feel so guilty not able to fix it. Now that I've finished all my applicaitons, I will make the repo better!

Does anyone know labs/professors that are looking for PhD studuents? My research interest is self-supervised learning(apparently). If you happen to know such a position, please contact me!

**Comment by Dongshengjiang** [comment]
best wishes!
