### ISSUE TITLE
For SimSiam, should be evaluation after backbone or encoder?

### ISSUE THREAD

**Issue by RealNewNoob** [PatrickHua/SimSiam#25]
I checked the linear_eval.py and noticed only the backbone is imported during the evaluation; this should be correct for SimCl. However, I think the learned representation in SimSiam should be the p after the encoder, which includes the backbone and projector. 
This might be the reason that others claim performance doesn't meet the original paper.

**Comment by PatrickHua** [comment]
I evaluated the projector output. It's two points lower than the encoder output.

It also feels like cheating when you can use extra layers for evaluation.
