### ISSUE TITLE
Do cifar_resnet_1.py and cifar_resnet_2.py are the same?

### ISSUE THREAD

**Issue by guixianjin** [PatrickHua/SimSiam#30]
Dear author:

     Do the following cifar_resnet_1.py and cifar_resnet_2.py are the same? If not, what's the difference between them?

       + https://github.com/PatrickHua/SimSiam/blob/main/models/backbones/cifar_resnet_1.py
       + https://github.com/PatrickHua/SimSiam/blob/main/models/backbones/cifar_resnet_2.py

    And are they the same as the network used in MoCo_cifar_10_demo ?
        + https://colab.research.google.com/github/facebookresearch/moco/blob/colab-notebook/colab/moco_cifar10_demo.ipynb

**Comment by PatrickHua** [comment]
the two cifar variants are the same, but from different sources.
They both use 3x3 kernel size in the first convolutional layer and removed max pooling.

**Comment by guixianjin** [comment]
I get it. Thanks for your prompt reply!  : )
